# Generated by cucumber-sinatra. (2013-11-13 14:45:13 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/myapp.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BorisBikes

class BorisBikesWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BorisBikesWorld.new
end
